version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: familia123
      MYSQL_DATABASE: crud-desafio
      MYSQL_PASSWORD: admin123
    ports:
      - '3300:3300'
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    command: yarn dev
    ports:
      - '3030:3030'
    volumes:
      - .:/app/server
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PASSWORD: admin123
      DB_NAME: crud-desafio

volumes:
  mysql_data:
